# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import metaci.plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20180314_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrepository',
            name='yaml_config',
            field=models.TextField(blank=True, null=True, validators=[metaci.plan.models.validate_yaml_field]),
        ),
    ]
